/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.test.ui.project;

//import adminui.AddTestInfo;
//import adminui.AddTestScheduleinfo;
//import adminui.MainScreen;
import javax.swing.JOptionPane;

import com.test.model.dao.LoginInfoDAO;
import com.test.model.to.LoginInfoTO;
import com.test.ui.admin.MainScreen;
import com.test.ui.user.UserMainScreen;
import com.test.utility.Validations;
//import test.operations.Validations;
//import userui.UserMainScreen;

/**
 *
 * @author user
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
        setVisible(true);
        setSize(800, 500);
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btnlogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        jtfusername = new javax.swing.JTextField();
        jtfpassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/test/ui/project/user.png"))); // NOI18N
        jLabel1.setText(" Username:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/test/ui/project/password.jpg"))); // NOI18N
        jLabel2.setText(" Password:");

        btnlogin.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/test/ui/project/login.png"))); // NOI18N
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        jtfusername.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jtfusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfusernameActionPerformed(evt);
            }
        });

        jtfpassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel4.setText("Login Screen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfusername, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(310, 310, 310))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfusername, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        String username = jtfusername.getText().trim();
        String password = new String(jtfpassword.getPassword());
        String message = "";
        if (Validations.isEmpty(username) || Validations.isEmpty(password)) {
            message = "Please Enter Some Value";
        } else {
            LoginInfoTO record = new LoginInfoDAO().checkUser(username);
            if (record != null) {
                if (record.getPassword().equals(password)) {
                    if (record.getRolename().equalsIgnoreCase("admin")) {
                        MainScreen obj = new MainScreen();
//                        obj.setUsername(username);
                        obj.setVisible(true);
                        if (record.getLastlogin() == null) {
                            message = " Welcome First Time Admin ";
                        } else {
                            message = " Welcome admin Your Last Visit : " + record.getLastlogin();
                        }
                        new LoginInfoDAO().updateLastLogin(username);
                        dispose();
                    } else if (record.getRolename().equalsIgnoreCase("user")) {
                        UserMainScreen obj = new UserMainScreen();
                        obj.setFusername(username);
                        obj.setVisible(true);
                        if (record.getLastlogin() == null) {
                            message = " Welcome First Time  " + username;
                        } else {
                            message = " Welcome " + username + " Your Last Visit : " + record.getLastlogin();
                        }
                        new LoginInfoDAO().updateLastLogin(username);
                        dispose();
                    } else if (record.getRolename().equalsIgnoreCase("student")) {
                        StudentMainScreen obj = new StudentMainScreen(username);
                        obj.setSusername(username);
                        obj.setVisible(true);
                        if (record.getLastlogin() == null) {
                            message = " Welcome First Time  " + username;
                        } else {
                            message = " Welcome " + username + " Your Last Visit : " + record.getLastlogin();
                        }
                        new LoginInfoDAO().updateLastLogin(username);
                        dispose();
                    } else {
                        message = "Invalid Credentials Not allowed";
                    }
                } else {
                    message = "Invalid Password";
                }
            } else {
                message = "Invalid User Name";
            }
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnloginActionPerformed

    private void jtfusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfusernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jtfpassword;
    private javax.swing.JTextField jtfusername;
    // End of variables declaration//GEN-END:variables
}
