/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.test.ui.project;

import java.awt.Desktop;
import java.beans.PropertyVetoException;
import java.util.List;
import com.test.model.dao.SubjectInfoDAO;
import com.test.model.dao.TestInfoDAO;
import com.test.model.dao.TestScheduleDAO;
import com.test.model.to.SubjectInfoTO;
import com.test.model.to.TestInfoTO;
import com.test.model.to.TestScheduleTO;
import javax.swing.JFrame;

/**
 *
 * @author user
 */
public class StudentMainScreen extends javax.swing.JFrame {

    private String susername;

    public String getSusername() {
        return susername;
    }

    public void setSusername(String susername) {
        this.susername = susername;
    }

    public StudentMainScreen() {
        initComponents();
        // Enable the maximize option
        

    }

    public StudentMainScreen(String username) {
        initComponents();
        susername = username;
        List<TestInfoTO> testschedules = new TestInfoDAO().getAllRecord(username);
        jcbtestschedule.removeAllItems();
        jcbtestschedule.addItem("Test Scheduled");
        if (testschedules != null && testschedules.size() > 0) {
            for (TestInfoTO cit : testschedules) {
                jcbtestschedule.addItem(cit);
            }
        }
        setSize(1000, 700);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentscreendeskpane = new javax.swing.JDesktopPane();
        jcbtestschedule = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnstarttest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        studentscreendeskpane.setPreferredSize(new java.awt.Dimension(640, 413));

        jcbtestschedule.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbtestschedule.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbtestschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbtestscheduleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("CHECK TEST ");

        btnstarttest.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnstarttest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/test/ui/project/start_test.jpg"))); // NOI18N
        btnstarttest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstarttestActionPerformed(evt);
            }
        });

        studentscreendeskpane.setLayer(jcbtestschedule, javax.swing.JLayeredPane.DEFAULT_LAYER);
        studentscreendeskpane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        studentscreendeskpane.setLayer(btnstarttest, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout studentscreendeskpaneLayout = new javax.swing.GroupLayout(studentscreendeskpane);
        studentscreendeskpane.setLayout(studentscreendeskpaneLayout);
        studentscreendeskpaneLayout.setHorizontalGroup(
            studentscreendeskpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentscreendeskpaneLayout.createSequentialGroup()
                .addGroup(studentscreendeskpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentscreendeskpaneLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jcbtestschedule, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(studentscreendeskpaneLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(btnstarttest, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(3, Short.MAX_VALUE))
        );
        studentscreendeskpaneLayout.setVerticalGroup(
            studentscreendeskpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentscreendeskpaneLayout.createSequentialGroup()
                .addGroup(studentscreendeskpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentscreendeskpaneLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(studentscreendeskpaneLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jcbtestschedule, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addComponent(btnstarttest, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        getContentPane().add(studentscreendeskpane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnstarttestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstarttestActionPerformed
        if (jcbtestschedule.getSelectedIndex() > 0) {
            TestInfoTO tit = (TestInfoTO) jcbtestschedule.getSelectedItem();
            TestInstructions ti = new TestInstructions(tit.getTestid(), susername);
            ti.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnstarttestActionPerformed

    private void jcbtestscheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbtestscheduleActionPerformed

    }//GEN-LAST:event_jcbtestscheduleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMainScreen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMainScreen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMainScreen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMainScreen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentMainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnstarttest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<Object> jcbtestschedule;
    private javax.swing.JDesktopPane studentscreendeskpane;
    // End of variables declaration//GEN-END:variables
}
