/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.test.ui.admin;

import java.util.List;
import javax.swing.JOptionPane;
import com.test.model.dao.SectionInfoDAO;
import com.test.model.dao.SubjectInfoDAO;
import com.test.model.to.SectionInfoTO;
import com.test.model.to.SubjectInfoTO;
import com.test.utility.Validations;

/**
 *
 * @author user
 */
public class AddSectionInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddSectionInfo
     */
    public AddSectionInfo() {

        initComponents();
        List<SubjectInfoTO> allsubjects = new SubjectInfoDAO().getAllRecord();
        jcbsubjectId.removeAllItems();
        jcbsubjectId.addItem("Subjects");
        if (allsubjects != null && allsubjects.size() > 0) {
            for (SubjectInfoTO cit : allsubjects) {
                jcbsubjectId.addItem(cit);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jtfsectionname = new javax.swing.JTextField();
        jtfsectionid = new javax.swing.JTextField();
        jcbsubjectId = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Section ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Section Name:");

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdd.setText("Add Subject Information");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Subject ID:");

        jtfsectionname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfsectionname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfsectionnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfsectionnameKeyTyped(evt);
            }
        });

        jtfsectionid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfsectionid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfsectionidActionPerformed(evt);
            }
        });
        jtfsectionid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfsectionidKeyTyped(evt);
            }
        });

        jcbsubjectId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbsubjectId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbsubjectId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbsubjectIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbsubjectId, 0, 211, Short.MAX_VALUE)
                    .addComponent(jtfsectionname)
                    .addComponent(jtfsectionid))
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btnAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfsectionid, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfsectionname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jcbsubjectId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        boolean allvalid = true;
        String message = "";
        String sectionid = jtfsectionid.getText().trim();
        String sectionname = jtfsectionname.getText().trim();
        if (jcbsubjectId.getSelectedIndex() == 0) {
            message = "Please Choose Any Subject";
            allvalid = false;
        }
        if (Validations.isEmpty(sectionid)) {
            message = "Please Enter Section ID";
            allvalid = false;
        }
        if (Validations.isEmpty(sectionname)) {
            message = "Please Enter Section Name";
            allvalid = false;
        }
        if (allvalid) {
            SectionInfoTO sit = new SectionInfoTO();
            SubjectInfoTO ssit = (SubjectInfoTO) jcbsubjectId.getSelectedItem();
            sit.setSubjectid(ssit.getSubjectid());
            sit.setSectionid(sectionid);
            sit.setSectionname(sectionname);
            SectionInfoDAO action=new SectionInfoDAO();
            if(action.insertRecord(sit))
            {
                message="Section Information Added In System";
            }
            else{
                message=action.getErrormessage();
            }
            
        }
        JOptionPane.showMessageDialog(this, message);

    }//GEN-LAST:event_btnAddActionPerformed

    private void jtfsectionnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfsectionnameKeyPressed

    }//GEN-LAST:event_jtfsectionnameKeyPressed

    private void jtfsectionnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfsectionnameKeyTyped
        if(Character.isDigit(evt.getKeyChar())){
                evt.consume();
            }

    }//GEN-LAST:event_jtfsectionnameKeyTyped

    private void jtfsectionidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfsectionidKeyTyped
            if(Character.isDigit(evt.getKeyChar())){
                evt.consume();
            }
    }//GEN-LAST:event_jtfsectionidKeyTyped

    private void jtfsectionidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfsectionidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfsectionidActionPerformed

    private void jcbsubjectIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbsubjectIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbsubjectIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<Object> jcbsubjectId;
    private javax.swing.JTextField jtfsectionid;
    private javax.swing.JTextField jtfsectionname;
    // End of variables declaration//GEN-END:variables
}
