/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.test.ui.admin;

import javax.swing.JOptionPane;
import com.test.model.dao.SubjectInfoDAO;
import com.test.model.to.SubjectInfoTO;
import com.test.utility.Validations;

/**
 *
 * @author user
 */
public class AddSubjectInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddStudentInfo
     */
    public AddSubjectInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jtfSubejctname = new javax.swing.JTextField();
        jtfdescription = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfSubjectID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Subject Information");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Description:");

        jtfSubejctname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfSubejctname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfSubejctnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfSubejctnameKeyTyped(evt);
            }
        });

        jtfdescription.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfdescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfdescriptionKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Subject ID:");

        jtfSubjectID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfSubjectID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfSubjectIDKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Subject Name:");

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdd.setText("Add Subject Information");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jtfdescription, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(btnAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 258, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtfSubejctname, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addComponent(jtfSubjectID))
                    .addGap(15, 15, 15)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfdescription, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jtfSubjectID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)
                    .addComponent(jtfSubejctname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(269, 269, 269)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfSubjectIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSubjectIDKeyTyped
        // TODO if(Character.isDigit(evt.getKeyChar()))
         if(Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }

    }//GEN-LAST:event_jtfSubjectIDKeyTyped

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String message = "";
        String subjectid=jtfSubjectID.getText();
        String subjectname=jtfSubejctname.getText();
        String description=jtfdescription.getText();
        if(Validations.isEmpty(subjectid)||Validations.isEmpty(subjectname)||Validations.isEmpty(description))
        {
            message="Please Fill All Boxes";
        }
        else{
            SubjectInfoTO sit=new SubjectInfoTO();
            sit.setSubjectid(subjectid);
            sit.setSubjectname(subjectname);
            sit.setDescription(description);
            SubjectInfoDAO sid=new SubjectInfoDAO();
            if(sid.insertRecord(sit)){
                message="Subject Information Added";
            }
            else{
                message=sid.getErrormessage();
            }
        }
        JOptionPane.showMessageDialog(this, message);

    }//GEN-LAST:event_btnAddActionPerformed

    private void jtfdescriptionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfdescriptionKeyTyped
        if(Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jtfdescriptionKeyTyped

    private void jtfSubejctnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSubejctnameKeyPressed
        
    }//GEN-LAST:event_jtfSubejctnameKeyPressed

    private void jtfSubejctnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSubejctnameKeyTyped
        // TODO if(Character.isDigit(evt.getKeyChar()))
         if(Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jtfSubejctnameKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jtfSubejctname;
    private javax.swing.JTextField jtfSubjectID;
    private javax.swing.JTextField jtfdescription;
    // End of variables declaration//GEN-END:variables
}
