/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.test.ui.admin;

import java.util.List;
import javax.swing.JOptionPane;
import com.test.model.dao.LoginInfoDAO;
import com.test.model.dao.SectionInfoDAO;
import com.test.model.dao.SubjectInfoDAO;
import com.test.model.dao.TestInfoDAO;
import com.test.model.dao.TestQuestionDAO;
import com.test.model.to.LoginInfoTO;
import com.test.model.to.SectionInfoTO;
import com.test.model.to.SubjectInfoTO;
import com.test.model.to.TestInfoTO;
import com.test.model.to.TestQuestionTO;
import com.test.utility.Validations;

/**
 *
 * @author user
 */
public class AddTestQuestionInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddTestQuestionInfo
     */
    public AddTestQuestionInfo() {
        initComponents();
        List<SectionInfoTO> sections = new SectionInfoDAO().getAllRecord();
        jcbsectionid.removeAllItems();
        jcbsectionid.addItem("Sections");
        if (sections != null && sections.size() > 0) {
            for (SectionInfoTO cit : sections) {
                jcbsectionid.addItem(cit);
            }
        }
        List<TestInfoTO> tests = new TestInfoDAO().getAllRecord();
        jcbtestid.removeAllItems();
        jcbtestid.addItem("Tests");
        if (tests != null && tests.size() > 0) {
            for (TestInfoTO cit : tests) {
                jcbtestid.addItem(cit);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfoptiona = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfoptionb = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfoptionc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfoptiond = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jcbanswer = new javax.swing.JComboBox<>();
        btnaddquestioninfo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jcbsectionid = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jtfmarks = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jcbtestid = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtfquestiontext = new javax.swing.JTextArea();

        jLabel6.setText("jLabel6");

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Question Information");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Question:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("   OPTION A:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("   OPTION B:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("   OPTION C:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("   OPTION D:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("CHOOSE ANSWER:");

        jcbanswer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jcbanswer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Answer", "a", "b", "c", "d" }));
        jcbanswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbanswerActionPerformed(evt);
            }
        });

        btnaddquestioninfo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnaddquestioninfo.setText("Add Question");
        btnaddquestioninfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddquestioninfoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("     SECTION ID:");

        jcbsectionid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbsectionid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("     MARKS:");

        jtfmarks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfmarksKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("     TEST ID:");

        jcbtestid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbtestid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbtestid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbtestidItemStateChanged(evt);
            }
        });

        jtfquestiontext.setColumns(20);
        jtfquestiontext.setRows(5);
        jScrollPane1.setViewportView(jtfquestiontext);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfoptionc, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(242, 242, 242))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfmarks, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbtestid, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbsectionid, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcbanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtfoptiona, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(125, 125, 125)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfoptionb, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(jtfoptiond))
                                .addGap(242, 242, 242))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(btnaddquestioninfo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfoptiona, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfoptionb, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfoptionc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfoptiond, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbtestid, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbsectionid, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfmarks, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(btnaddquestioninfo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddquestioninfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddquestioninfoActionPerformed
        boolean allvalid = true;
        String message = "";
        String question = jtfquestiontext.getText().trim();
        String optiona = jtfoptiona.getText().trim();
        String optionb = jtfoptionb.getText().trim();
        String optionc = jtfoptionc.getText().trim();
        String optiond = jtfoptiond.getText().trim();
        String marks = jtfmarks.getText().trim();
        String answer = (String) jcbanswer.getSelectedItem();
        if (Validations.isEmpty(question)) {
            message = "Please Enter The text In Question Box";
            allvalid = false;
        }
        if (Validations.isEmpty(optiona)) {
            message = "Please Enter Option A";
            allvalid = false;
        }
        if (Validations.isEmpty(optionb)) {
            message = "Please Enter Option B";
            allvalid = false;
        }
        if (Validations.isEmpty(optionc)) {
            message = "Please Enter Option C";
            allvalid = false;
        }
        if (Validations.isEmpty(optiond)) {
            message = "Please Enter Option D";
            allvalid = false;
        }
        if (jcbanswer.getSelectedIndex() == 0) {
            message = "Please Choose Answer";
            allvalid = false;
        }
        if (jcbtestid.getSelectedIndex() == 0) {
            message = "Please Choose Test ID";
            allvalid = false;
        }
        if (jcbsectionid.getSelectedIndex() == 0) {
            message = "Please Choose Section";
            allvalid = false;
        }
        if (Validations.isEmpty(marks)) {
            message = "Please Enter Marks";
            allvalid = false;
        }
        if (allvalid) {
            TestQuestionTO tqi = new TestQuestionTO();
            tqi.setQuestiontext(question);
            tqi.setOptiona(optiona);
            tqi.setOptionb(optionb);
            tqi.setOptionc(optionc);
            tqi.setOptiond(optiond);
            int marks1 = Integer.parseInt(marks);
            tqi.setMarks(marks1);
            TestInfoTO tit = (TestInfoTO) jcbtestid.getSelectedItem();
            tqi.setTestid(tit.getTestid());
            SectionInfoTO sit = (SectionInfoTO) jcbsectionid.getSelectedItem();
            tqi.setSectionid(sit.getSectionid());

            tqi.setAnswer(answer);
            TestQuestionDAO tqd = new TestQuestionDAO();
            if (tqd.insertRecord(tqi)) {
                message = "Question Is Added In The System";
            } else {
                message = tqd.getErrormessage();
            }
            JOptionPane.showMessageDialog(this, message);
        }

    }//GEN-LAST:event_btnaddquestioninfoActionPerformed

    private void jtfmarksKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfmarksKeyPressed
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();;
        }
    }//GEN-LAST:event_jtfmarksKeyPressed

    private void jcbanswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbanswerActionPerformed

    }//GEN-LAST:event_jcbanswerActionPerformed

    private void jcbtestidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbtestidItemStateChanged
        jcbsectionid.removeAllItems();
        jcbsectionid.addItem("Sections");
        if (jcbtestid.getSelectedIndex() > 0) {

            TestInfoTO tit = (TestInfoTO) jcbtestid.getSelectedItem();
            List<SectionInfoTO> sections = new SectionInfoDAO().getAllRecord(Integer.toString(tit.getTestid()));
            if (sections != null && sections.size() > 0) {
                for (SectionInfoTO sit : sections) {
                    jcbsectionid.addItem(sit);
                }
            }
        }

    }//GEN-LAST:event_jcbtestidItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddquestioninfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Object> jcbanswer;
    private javax.swing.JComboBox<Object> jcbsectionid;
    private javax.swing.JComboBox<Object> jcbtestid;
    private javax.swing.JTextField jtfmarks;
    private javax.swing.JTextField jtfoptiona;
    private javax.swing.JTextField jtfoptionb;
    private javax.swing.JTextField jtfoptionc;
    private javax.swing.JTextField jtfoptiond;
    private javax.swing.JTextArea jtfquestiontext;
    // End of variables declaration//GEN-END:variables
}
