/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.test.ui.admin;

import java.awt.GridLayout;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import com.test.model.dao.LoginInfoDAO;
import com.test.model.dao.TestInfoDAO;
import com.test.model.dao.TestScheduleDAO;
import com.test.model.to.LoginInfoTO;
import com.test.model.to.SubjectInfoTO;
import com.test.model.to.TestInfoTO;
import com.test.model.to.TestScheduleTO;

/**
 *
 * @author user
 */
public class AddTestScheduleinfo extends javax.swing.JInternalFrame {

    private String fusername;
    private List<JCheckBox> checks;

    public String getFusername() {
        return fusername;
    }

    public void setFusername(String fusername) {
        this.fusername = fusername;
    }

    public AddTestScheduleinfo() {

        initComponents();
        List<LoginInfoTO> students = new LoginInfoDAO().getAllstudents();
        jcbsurname.removeAllItems();
        jcbsurname.addItem("Students");
        if (students != null && students.size() > 0) {
            checks = new ArrayList<>();
            int rows = students.size() / 3 + 1;
            GridLayout layout = new GridLayout(rows, 3, 5, 5);
            panelUsers.setLayout(layout);
            for (LoginInfoTO cit : students) {
                JCheckBox jcb = new JCheckBox(cit.getUsername());
                jcb.setSelected(true);
                panelUsers.add(jcb);
                checks.add(jcb);
                jcbsurname.addItem(cit);
            }

        }

        List<TestInfoTO> tests = new TestInfoDAO().getAllRecord();
        jcbtestid.removeAllItems();
        jcbtestid.addItem("Tests");
        if (tests != null && tests.size() > 0) {
            for (TestInfoTO cit : tests) {
                jcbtestid.addItem(cit);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbsurname = new javax.swing.JComboBox<>();
        jcbtestid = new javax.swing.JComboBox<>();
        btnaddtestschedule = new javax.swing.JButton();
        panelUsers = new javax.swing.JPanel();
        myFutureDatePanel1 = new com.test.ui.admin.MyFutureDatePanel();

        setClosable(true);
        setIconifiable(true);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("    SUSERNAME:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("    TEST DATE:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("    TEST ID:");

        jcbsurname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbsurname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbsurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbsurnameActionPerformed(evt);
            }
        });

        jcbtestid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbtestid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnaddtestschedule.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnaddtestschedule.setText("Add Test Schedule");
        btnaddtestschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddtestscheduleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUsersLayout = new javax.swing.GroupLayout(panelUsers);
        panelUsers.setLayout(panelUsersLayout);
        panelUsersLayout.setHorizontalGroup(
            panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );
        panelUsersLayout.setVerticalGroup(
            panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(myFutureDatePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jcbsurname, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jcbtestid, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btnaddtestschedule, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbsurname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myFutureDatePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jcbtestid, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnaddtestschedule, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbsurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbsurnameActionPerformed

    }//GEN-LAST:event_jcbsurnameActionPerformed

    private void btnaddtestscheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddtestscheduleActionPerformed
        String message = "";
        List<String> selected = new ArrayList<>();
        if (checks != null && checks.size() > 0) {
            for (JCheckBox jcb : checks) {
                if (jcb.isSelected()) {
                    selected.add(jcb.getText());
                }
            }
        }
        if (selected.size() == 0) {
            message = "Please choose Student";
        } else if (jcbtestid.getSelectedIndex() == 0) {
            message = "Please select Test";
        } else {
            //LoginInfoTO student = (LoginInfoTO) jcbsurname.getSelectedItem();
            TestScheduleTO tst = new TestScheduleTO();
            //tst.setSusername(student.toString());
            tst.setFusername(getFusername());
            tst.setTestdate(myFutureDatePanel1.getSelectedDate());
            TestInfoTO test = (TestInfoTO) jcbtestid.getSelectedItem();
            tst.setTestid(test.getTestid());
            TestScheduleDAO tid = new TestScheduleDAO();
            for (String username : selected) {
                tst.setSusername(username);
                if (tid.insertRecord(tst)) {
                    message += username + " Test is Schedule Added In The System";
                } else {
                    message += username +" is not scheduled. " + tid.getErrormessage();
                }
            }

        }
        JOptionPane.showMessageDialog(this, message);

    }//GEN-LAST:event_btnaddtestscheduleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddtestschedule;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<Object> jcbsurname;
    private javax.swing.JComboBox<Object> jcbtestid;
    private com.test.ui.admin.MyFutureDatePanel myFutureDatePanel1;
    private javax.swing.JPanel panelUsers;
    // End of variables declaration//GEN-END:variables
}
