/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.test.ui.admin;

import java.beans.PropertyVetoException;
import javax.swing.ImageIcon;
import com.test.model.dao.DataConnection;

/**
 *
 * @author user
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    
    private String username;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
    public MainScreen() {
        setIconImage(new ImageIcon(getClass().getResource("/com/test/ui/admin/app_store.png")).getImage());
        initComponents();
        setVisible(true);
        setSize(1000, 600);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskpane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmiLogininfo = new javax.swing.JMenuItem();
        jmiViewLoginInfo = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmiAddsubjectinfo = new javax.swing.JMenuItem();
        jmiViewsubjectinfo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        AddSectionInformation = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiViewTestInfo = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmiaddquestioninfo = new javax.swing.JMenuItem();
        jmiviewquestioninfo = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmiaddtestschedule = new javax.swing.JMenuItem();
        jmiviewtestschedule = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jmiviewresultinfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Evaluation System");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout deskpaneLayout = new javax.swing.GroupLayout(deskpane);
        deskpane.setLayout(deskpaneLayout);
        deskpaneLayout.setHorizontalGroup(
            deskpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1198, Short.MAX_VALUE)
        );
        deskpaneLayout.setVerticalGroup(
            deskpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );

        getContentPane().add(deskpane, java.awt.BorderLayout.CENTER);

        jMenu2.setText("Login Info Operations");

        jmiLogininfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/test/ui/admin/addd.png"))); // NOI18N
        jmiLogininfo.setText("Add Login Info");
        jmiLogininfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogininfoActionPerformed(evt);
            }
        });
        jMenu2.add(jmiLogininfo);

        jmiViewLoginInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/test/ui/admin/vieww.png"))); // NOI18N
        jmiViewLoginInfo.setText("View Login Information");
        jmiViewLoginInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewLoginInfoActionPerformed(evt);
            }
        });
        jMenu2.add(jmiViewLoginInfo);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Subject Info Operations");

        jmiAddsubjectinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/test/ui/admin/addd.png"))); // NOI18N
        jmiAddsubjectinfo.setText("Add Subject Information");
        jmiAddsubjectinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddsubjectinfoActionPerformed(evt);
            }
        });
        jMenu1.add(jmiAddsubjectinfo);

        jmiViewsubjectinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/test/ui/admin/vieww.png"))); // NOI18N
        jmiViewsubjectinfo.setText("View Subject Information");
        jmiViewsubjectinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewsubjectinfoActionPerformed(evt);
            }
        });
        jMenu1.add(jmiViewsubjectinfo);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Section Info Operations");

        AddSectionInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/test/ui/admin/addd.png"))); // NOI18N
        AddSectionInformation.setText("Add Section Information");
        AddSectionInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSectionInformationActionPerformed(evt);
            }
        });
        jMenu3.add(AddSectionInformation);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/test/ui/admin/vieww.png"))); // NOI18N
        jMenuItem2.setText("View Section Information");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Test Info Operations");

        jmiViewTestInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/test/ui/admin/addd.png"))); // NOI18N
        jmiViewTestInfo.setText("Add Test Information");
        jmiViewTestInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewTestInfoActionPerformed(evt);
            }
        });
        jMenu4.add(jmiViewTestInfo);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/test/ui/admin/vieww.png"))); // NOI18N
        jMenuItem3.setText("View Test Information");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Question Info Operations");

        jmiaddquestioninfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/test/ui/admin/addd.png"))); // NOI18N
        jmiaddquestioninfo.setText("Add Question Information");
        jmiaddquestioninfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiaddquestioninfoActionPerformed(evt);
            }
        });
        jMenu5.add(jmiaddquestioninfo);

        jmiviewquestioninfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/test/ui/admin/vieww.png"))); // NOI18N
        jmiviewquestioninfo.setText("View Question Information");
        jmiviewquestioninfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiviewquestioninfoActionPerformed(evt);
            }
        });
        jMenu5.add(jmiviewquestioninfo);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Test Schedule Operations");

        jmiaddtestschedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/test/ui/admin/addd.png"))); // NOI18N
        jmiaddtestschedule.setText("Add Test Schedule");
        jmiaddtestschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiaddtestscheduleActionPerformed(evt);
            }
        });
        jMenu6.add(jmiaddtestschedule);

        jmiviewtestschedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/test/ui/admin/vieww.png"))); // NOI18N
        jmiviewtestschedule.setText("View Test Schedule");
        jmiviewtestschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiviewtestscheduleActionPerformed(evt);
            }
        });
        jMenu6.add(jmiviewtestschedule);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Result Information Operations");

        jmiviewresultinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/test/ui/admin/vieww.png"))); // NOI18N
        jmiviewresultinfo.setText("View Result Info");
        jmiviewresultinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiviewresultinfoActionPerformed(evt);
            }
        });
        jMenu7.add(jmiviewresultinfo);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        DataConnection.closeConnection();
    }//GEN-LAST:event_formWindowClosing

    private void jmiLogininfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogininfoActionPerformed
        AddLoginInfo ali = new AddLoginInfo();
        ali.setVisible(true);
        deskpane.add(ali);
        try {
            ali.setSelected(true);

        } catch (PropertyVetoException ex) {

        }

    }//GEN-LAST:event_jmiLogininfoActionPerformed

    private void jmiViewLoginInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewLoginInfoActionPerformed
        ViewLoginInfo vci = new ViewLoginInfo();
        vci.setVisible(true);
        deskpane.add(vci);
        try {
            vci.setSelected(true);

        } catch (PropertyVetoException ex) {

        }


    }//GEN-LAST:event_jmiViewLoginInfoActionPerformed

    private void jmiAddsubjectinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddsubjectinfoActionPerformed
        AddSubjectInfo asi = new AddSubjectInfo();
        asi.setVisible(true);
        deskpane.add(asi);
        try {
            asi.setSelected(true);
        } catch (PropertyVetoException ex) {

        }

    }//GEN-LAST:event_jmiAddsubjectinfoActionPerformed

    private void jmiViewsubjectinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewsubjectinfoActionPerformed

        ViewSubjectInfo vsi = new ViewSubjectInfo();
        vsi.setVisible(true);
        deskpane.add(vsi);
        try {
            vsi.setSelected(true);

        } catch (PropertyVetoException ex) {

        }

    }//GEN-LAST:event_jmiViewsubjectinfoActionPerformed

    private void AddSectionInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSectionInformationActionPerformed
        AddSectionInfo vsi = new AddSectionInfo();
        vsi.setVisible(true);
        deskpane.add(vsi);
        try {
            vsi.setSelected(true);

        } catch (PropertyVetoException ex) {

        }
    }//GEN-LAST:event_AddSectionInformationActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ViewSectionInfo vsi = new ViewSectionInfo();
        vsi.setVisible(true);
        deskpane.add(vsi);
        try {
            vsi.setSelected(true);

        } catch (PropertyVetoException ex) {

        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmiViewTestInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewTestInfoActionPerformed
        AddTestInfo vsi = new AddTestInfo();
        vsi.setVisible(true);
        deskpane.add(vsi);
        try {
            vsi.setSelected(true);

        } catch (PropertyVetoException ex) {

        }
    }//GEN-LAST:event_jmiViewTestInfoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ViewTestInfo vsi = new ViewTestInfo();
        vsi.setVisible(true);
        deskpane.add(vsi);
        try {
            vsi.setSelected(true);

        } catch (PropertyVetoException ex) {

        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jmiaddquestioninfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiaddquestioninfoActionPerformed
       AddTestQuestionInfo vsi = new AddTestQuestionInfo();
        vsi.setVisible(true);
        deskpane.add(vsi);
        try {
            vsi.setSelected(true);

        } catch (PropertyVetoException ex) {

        }
    }//GEN-LAST:event_jmiaddquestioninfoActionPerformed

    private void jmiviewquestioninfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiviewquestioninfoActionPerformed
        ViewTestQuestioninfo vsi = new ViewTestQuestioninfo();
        vsi.setVisible(true);
        deskpane.add(vsi);
        try {
            vsi.setSelected(true);

        } catch (PropertyVetoException ex) {

        }
    }//GEN-LAST:event_jmiviewquestioninfoActionPerformed

    private void jmiaddtestscheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiaddtestscheduleActionPerformed
        AddTestScheduleinfo vsi = new AddTestScheduleinfo();
        vsi.setFusername(username);
        vsi.setVisible(true);
        deskpane.add(vsi);
        try {
            vsi.setSelected(true);

        } catch (PropertyVetoException ex) {

        }
    }//GEN-LAST:event_jmiaddtestscheduleActionPerformed

    private void jmiviewtestscheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiviewtestscheduleActionPerformed
        ViewTestscheduleinfo vsi = new ViewTestscheduleinfo();
        vsi.setVisible(true);
        deskpane.add(vsi);
        try {
            vsi.setSelected(true);

        } catch (PropertyVetoException ex) {

        }
    }//GEN-LAST:event_jmiviewtestscheduleActionPerformed

    private void jmiviewresultinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiviewresultinfoActionPerformed
        ViewResultInfo vsi = new ViewResultInfo();
        vsi.setVisible(true);
        deskpane.add(vsi);
        try {
            vsi.setSelected(true);

        } catch (PropertyVetoException ex) {

        }
    }//GEN-LAST:event_jmiviewresultinfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddSectionInformation;
    private javax.swing.JDesktopPane deskpane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jmiAddsubjectinfo;
    private javax.swing.JMenuItem jmiLogininfo;
    private javax.swing.JMenuItem jmiViewLoginInfo;
    private javax.swing.JMenuItem jmiViewTestInfo;
    private javax.swing.JMenuItem jmiViewsubjectinfo;
    private javax.swing.JMenuItem jmiaddquestioninfo;
    private javax.swing.JMenuItem jmiaddtestschedule;
    private javax.swing.JMenuItem jmiviewquestioninfo;
    private javax.swing.JMenuItem jmiviewresultinfo;
    private javax.swing.JMenuItem jmiviewtestschedule;
    // End of variables declaration//GEN-END:variables
}
