/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.test.ui.admin;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import com.test.model.dao.SectionInfoDAO;
import com.test.model.dao.SubjectInfoDAO;
import com.test.model.to.SectionInfoTO;
import com.test.model.to.SubjectInfoTO;

/**
 *
 * @author user
 */
public class ViewSectionInfo extends javax.swing.JInternalFrame {
    List<SectionInfoTO> courses;

    /**
     * Creates new form ViewSectionInfo
     */
    public ViewSectionInfo() {
        initComponents();
         bindTableLoginInfo();
    }
     private void bindTableLoginInfo() {
        courses = new SectionInfoDAO().getAllRecord();
        String[] colnames = {"Section ID", "Section Name","Subject ID"};
        Object[][] records = null;
        if (courses != null && courses.size() > 0) {
            records = new Object[courses.size()][colnames.length];
            int i = 0;
            for (SectionInfoTO sit : courses) {
                records[i] = new Object[]{sit.getSectionid(), sit.getSectionname(),sit.getSubjectid()};
                i++;
            }
        } else {
            records = new Object[1][colnames.length];
            records[0] = new Object[]{"There is No Record", "There is No Record","There is No Record"};
        }
       
        DefaultTableModel dtm = new DefaultTableModel(records, colnames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableViewSectionInfo.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableViewSectionInfo = new javax.swing.JTable();
        btnrefreshSectioninfo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("View Section Information");
        setPreferredSize(new java.awt.Dimension(691, 483));

        tableViewSectionInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableViewSectionInfo);

        btnrefreshSectioninfo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnrefreshSectioninfo.setText("Refresh The Table");
        btnrefreshSectioninfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshSectioninfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addComponent(btnrefreshSectioninfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnrefreshSectioninfo, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrefreshSectioninfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshSectioninfoActionPerformed
        bindTableLoginInfo();
    }//GEN-LAST:event_btnrefreshSectioninfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnrefreshSectioninfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableViewSectionInfo;
    // End of variables declaration//GEN-END:variables
}
