/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.test.ui.admin;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import com.test.model.dao.SubjectInfoDAO;
import com.test.model.dao.TestInfoDAO;
import com.test.model.dao.TestQuestionDAO;
import com.test.model.to.SubjectInfoTO;
import com.test.model.to.TestInfoTO;
import com.test.model.to.TestQuestionTO;

/**
 *
 * @author user
 */
public class ViewTestQuestioninfo extends javax.swing.JInternalFrame {
    List<TestQuestionTO> questions;
     

    public ViewTestQuestioninfo() {
        initComponents();
        List<TestInfoTO> alltests = new TestInfoDAO().getAllRecord();
        jcbtestname.removeAllItems();
        jcbtestname.addItem("Tests");
        if (alltests != null && alltests.size() > 0) {
            for (TestInfoTO cit : alltests) {
                jcbtestname.addItem(cit);
            }
        }
         bindTableCourseInfo();
    }
     private void bindTableCourseInfo() {
     
        String[] colnames = {"Question ID", "Question", "Option A","Option B","Option C","Option D"};
        Object[][] records = null;
        if (questions != null && questions.size() > 0) {
            records = new Object[questions.size()][colnames.length];
            int i = 0;
            for (TestQuestionTO cit : questions) {
                records[i] = new Object[]{cit.getQuestionid(), cit.getQuestiontext(), cit.getOptiona(),cit.getOptionb(),cit.getOptionc(),cit.getOptiond()};
                i++;
            }
        } else {
            records = new Object[1][colnames.length];
            records[0] = new Object[]{"There is No Record", "There is No Record", "There is No Record","There is No Record","There is No Record","There is No Record"};
        }
        DefaultTableModel dtm = new DefaultTableModel(records, colnames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableViewtestquestioninfo.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableViewtestquestioninfo = new javax.swing.JTable();
        jcbtestname = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("Test Question Information");

        tableViewtestquestioninfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableViewtestquestioninfo);

        jcbtestname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbtestname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbtestname.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbtestnameItemStateChanged(evt);
            }
        });
        jcbtestname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbtestnameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jcbtestname, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbtestname, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbtestnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbtestnameActionPerformed
      
    }//GEN-LAST:event_jcbtestnameActionPerformed

    private void jcbtestnameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbtestnameItemStateChanged
      if(jcbtestname.getSelectedIndex() > 0){
            TestInfoTO cit = (TestInfoTO)jcbtestname.getSelectedItem();
            questions = new TestQuestionDAO().getAllRecordbytestid(cit.getTestid());
            bindTableCourseInfo();
        }
    }//GEN-LAST:event_jcbtestnameItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Object> jcbtestname;
    private javax.swing.JTable tableViewtestquestioninfo;
    // End of variables declaration//GEN-END:variables
}
