/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.test.ui.admin;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import com.test.model.dao.SectionInfoDAO;
import com.test.model.dao.TestScheduleDAO;
import com.test.model.to.SectionInfoTO;
import com.test.model.to.TestInfoTO;
import com.test.model.to.TestScheduleTO;

/**
 *
 * @author user
 */
public class ViewTestscheduleinfo extends javax.swing.JInternalFrame {

    List<TestScheduleTO> tests;

    public ViewTestscheduleinfo() {
        initComponents();
        bindTableLoginInfo();
    }

    private void bindTableLoginInfo() {
        tests = new TestScheduleDAO().getAllRecord();
        String[] colnames = {"Schedule ID", "Fusername", "Susername","Test Name","Test Date"};
        Object[][] records = null;
        if (tests != null && tests.size() > 0) {
            records = new Object[tests.size()][colnames.length];
            int i = 0;
            for (TestScheduleTO sit : tests) {
                records[i] = new Object[]{sit.getScheduleid(), sit.getFusername(), sit.getSusername(),sit.getTestname(),sit.getTestdate()};
                i++;
            }
        } else {
            records = new Object[1][colnames.length];
            records[0] = new Object[]{"There is No Record", "There is No Record", "There is No Record","There is No Record","There is No Record"};
        }

        DefaultTableModel dtm = new DefaultTableModel(records, colnames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabletestscheduleinfo.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabletestscheduleinfo = new javax.swing.JTable();
        btnrefreshtestscheduleinfo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(660, 489));

        tabletestscheduleinfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabletestscheduleinfo);

        btnrefreshtestscheduleinfo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnrefreshtestscheduleinfo.setText("Refresh The Table");
        btnrefreshtestscheduleinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshtestscheduleinfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnrefreshtestscheduleinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnrefreshtestscheduleinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrefreshtestscheduleinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshtestscheduleinfoActionPerformed
            bindTableLoginInfo();
    }//GEN-LAST:event_btnrefreshtestscheduleinfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnrefreshtestscheduleinfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabletestscheduleinfo;
    // End of variables declaration//GEN-END:variables
}
